// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXiQyYz7p7aBL2mL4FZAZaSCgkIBU3-fY',
    appId: '1:1016837882395:web:9f866a67cd3bab2e016ebe',
    messagingSenderId: '1016837882395',
    projectId: 'myapp-b8ffe',
    authDomain: 'myapp-b8ffe.firebaseapp.com',
    storageBucket: 'myapp-b8ffe.firebasestorage.app',
    measurementId: 'G-PRNBMZCPMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztl2PwnMahDNSzBqVZe7dYwfzqqNFBh8',
    appId: '1:1016837882395:android:345504fc52cacc25016ebe',
    messagingSenderId: '1016837882395',
    projectId: 'myapp-b8ffe',
    storageBucket: 'myapp-b8ffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUdvno6pjHsvZZZaD3kbmMjLOiHtvfOtI',
    appId: '1:1016837882395:ios:d624d7f298c04429016ebe',
    messagingSenderId: '1016837882395',
    projectId: 'myapp-b8ffe',
    storageBucket: 'myapp-b8ffe.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUdvno6pjHsvZZZaD3kbmMjLOiHtvfOtI',
    appId: '1:1016837882395:ios:d624d7f298c04429016ebe',
    messagingSenderId: '1016837882395',
    projectId: 'myapp-b8ffe',
    storageBucket: 'myapp-b8ffe.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXiQyYz7p7aBL2mL4FZAZaSCgkIBU3-fY',
    appId: '1:1016837882395:web:d0a585675263f011016ebe',
    messagingSenderId: '1016837882395',
    projectId: 'myapp-b8ffe',
    authDomain: 'myapp-b8ffe.firebaseapp.com',
    storageBucket: 'myapp-b8ffe.firebasestorage.app',
    measurementId: 'G-8F1S65JCNV',
  );
}
